version: "3.8"
services:
  http_dev:
    build:
      context: ./docker/presentation
      args:
        - PHP_VERSION=${PHP_VERSION}
    volumes:
      - ./app:/project
      - ./data/presentation_logs:/var/log/apache2
    working_dir: /project
    ports:
      - "${HTTP_PORT}:80"
    restart: always
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal
      ENV: dev
    links:
      - db_dev
      - redis
      - mailhog
    networks:
      - uatadmin
      - default
  db_dev:
    env_file:
      - ./.env
    image: mariadb:10.6.0
    volumes:
      - ./docker/data/mysqldata:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    restart: "always"
  phpmyadmin_dev:
    image: phpmyadmin/phpmyadmin:5.1.0-fpm-alpine
    environment:
      PMA_HOST: db_dev
      MYSQL_ROOT_PASSWORD: root
      UPLOAD_LIMIT: 1G
    restart: always
    ports:
      - "90:80"
    depends_on:
      - db_dev
  redis:
    image: library/redis:6
    restart: "always"
  mailhog:
    image: mailhog/mailhog
    logging:
      driver: 'none'  # disable saving logs
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui
    restart: "always"
networks:
  uatadmin:
    name: ${NETWORK_NAME}