version: "3.8"
services:
  http:
    build:
      context: ./docker/presentation-prod
      args:
        - PHP_VERSION=${PHP_VERSION}
    volumes:
      - ./app:/project
      - ./data/presentation_logs:/var/log/apache2
    working_dir: /project
    ports:
      - "${HTTP_PORT}:80"
    restart: always
    environment:
      ENV: prod
    links:
      - db
      - redis
    networks:
      - uatadmin
      - default
  db:
    env_file:
      - ./.env
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
    restart: "always"
    volumes:
      - /mysql/${COMPOSE_PROJECT_NAME}:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
  redis:
    image: library/redis:6
    restart: "always"
networks:
  uatadmin:
    external:
      name: ${NETWORK_NAME}